apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
type: Opaque
data:
  APP_SECRET: {{ .Values.secret.APP_SECRET | quote }}
  ADMIN_PASSWORD: {{ .Values.secret.ADMIN_PASSWORD | quote }}
