---
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-demo-app
  namespace: demo-app
  labels:
    app: k8s-demo
spec:
  ttlSecondsAfterFinished: 180
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seeder
          image: curlimages/curl:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              for i in $(seq 1 30); do
                curl -sf http://demo-app/health && break
                sleep 2
              done
              curl -X POST http://demo-app/api/notes \
                -H "Content-Type: application/json" \
                -d '{"title":"Note Seedée", "content": "Créée par le Job (seed-demo-app) K8s!", "category":"idea"}'
