apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-mypvc
  namespace: demo-app
  labels:
    app: k8s-demo
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-storage
