apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  namespace: demo-app
  labels:
    app: k8s-demo
type: Opaque
data:
  APP_SECRET: U2VjcmV0S2V5SGF5ZXQyMDI2IQ==
  ADMIN_PASSWORD: QWRtaW5QYXNzSGF5ZXQyMDI2IQ==
